depot/config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  resources :questions

  get 'admin' => 'admin#index'
  controller :sessions do
   get 'login' => :new
   post 'login' => :create
   delete 'logout' => :destroy
  end

  get 'contact' => 'blogs#contact'
  get 'sessions/create'

  get 'sessions/destroy'
  
  resources :products
  resources :users

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
  

 

end

depot/app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :name, :content, presence: true
end

depot/app/models/cart.rb
class Cart < ActiveRecord::Base
 has_many :line_items, dependent: :destroy

 def add_product(product_id)
  current_item = line_items.find_by(product_id: product_id)
  if current_item
   current_item.quantity += 1
  else
   current_item = line_items.build(product_id: product_id)
  end
   current_item
 end

 def total_price
   line_items.to_a.sum { |item| item.total_price }
 end

end

depot/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end

end

depot/app/models/order.rb
class Order < ActiveRecord::Base
 has_many :line_items, dependent: :destroy

 PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
 validates :name, :address, :email, presence: true
 validates :pay_type, inclusion: PAYMENT_TYPES

 def add_line_items_from_cart(cart)
  cart.line_items.each do |item|
   item.cart_id = nil
   line_items << item
  end
end

end

depot/app/models/product.rb
class Product < ActiveRecord::Base
 has_many :line_items
 before_destroy :ensure_not_referenced_by_any_line_item
validates :title, :description, :image_url, presence: true
 validates :price, numericality: {greater_than_or_equal_to: 0.01}
 validates :title, uniqueness: true
 
 validates :image_url, allow_blank: true, format: {
 with:    %r{\.(gif|jpeg|jpg|png)\Z}i,
 message: 'must be a URL for GIF, JPEG, JPG or PNG image.'
}


private
# ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
     return true
    else
     errors.add(:base, 'Line Items present')
     return false
    end
  end
  def self.latest
   Product.order(:updated_at).last
  end

end

depot/app/models/question.rb
class Question < ActiveRecord::Base
	validates :name, :email, :ques, presence: true
end

depot/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains


  private
   def ensure_an_admin_remains
     if User.count.zero?
        raise "Can't delete last user"
     end
   end
end

depot/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
   @total_orders = Order.count
  end
end

depot/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :new, :create, :contact]
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'News was successfully added.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :content)
    end

    def contact

    end
end

depot/app/helpers/admin_helper.rb
module AdminHelper
end

depot/app/helpers/application_helper.rb
module ApplicationHelper

 def hidden_div_if(condition, attributes = {}, &block)
   if condition
     attributes["style"] = "display: none"
   end
   content_tag("div", attributes, &block)
 end

end

depot/app/helpers/blogs_helper.rb
module BlogsHelper
end

depot/app/helpers/carts_helper.rb
module CartsHelper
end

depot/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depot/app/helpers/orders_helper.rb
module OrdersHelper
end

depot/app/helpers/products_helper.rb
module ProductsHelper
end

depot/app/helpers/questions_helper.rb
module QuestionsHelper
end

depot/app/helpers/sessions_helper.rb
module SessionsHelper
end

depot/app/helpers/store_helper.rb
module StoreHelper
end

depot/app/helpers/users_helper.rb
module UsersHelper
end

depot/app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
   <%= form_tag store_path, class: 'locale' do %>
    <%= select_tag 'set_locale',
      options_for_select(LANGUAGES, I18n.locale.to_s),
      onchange: 'this.form.submit()' %>
    <%= submit_tag 'submit' %>
    <%= javascript_tag "$('.locale input').hide()" %>
<% end %>

   <%= image_tag("logo.jpeg") %>
   <h2><%= @page_title || t('.title') %></h2>
  </div>
  
    <div id="columns">
      <div id="side">
        <% if @cart %>
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
            <%= render @cart %>
          <% end %>
        <% end %>
        <ul>
          <% if session[:user_id] %>
              <li><%=link_to t('.home'), admin_path %></li>
              <li><%= link_to 'Questions', questions_path %></li>
              <li><%= link_to 'News', blogs_path %></li>
              <li><%= link_to 'Orders', orders_path%></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users', users_path %></li>
              </ul>
              <%= button_to 'Logout', logout_path, method: :delete %>
              <%else%>
              <li><%= link_to t('.home'), store_path %></li>
              <li><%=link_to t('.questions'),new_question_path %></li>
              <li><%=link_to t('.news'), blogs_path %></li>
              <li><%=link_to t('.contact'), contact_path %></a></li>
              </ul>
          <% end %>

      </div>
    
      <div id="main"> 
        <%= yield %>
      </div>
    </div>
</body>
</html>

depot/app/views/order_notifier/received.html.erb
Dear <%= @order.name %>
<h1>Order Received</h1>
<p>
Thank you for your recent order from The Pragmatic Store.
</p>
You ordered the following items:
<%= render @order.line_items %>
We'll send you a separate e-mail when your order ships.

depot/app/views/order_notifier/received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from The Pragmatic Store.
You ordered the following items:
<%= render @order.line_items -%>
We'll send you a separate e-mail when your order ships.

depot/app/views/order_notifier/shipped.html.erb
<h3>Pragmatic Order Shipped</h3>
<p>
This is just to let you know that we've shipped your recent order:
</p>
<table>
<tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items -%>
</table>

depot/app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/order_notifier/shipped.text.erb